version: "3"

services:
  broker-service:
    build:
      context: ./../broker-services
      dockerfile: ./../broker-services/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
